#!/usr/bin/env python
import socket

s = None
port = 9999
hostname = ""

hostname = raw_input("Enter a username : ")
"""ip_connect = "192.168.0.106"""
ip_connect = raw_input("Enter IP to connect to: ")
print "Connecting to " + ip_connect
""" Don't believe I need this """
"""
port = raw_input("Enter a port to connect to: ")
while True:
	try:
		int(port)
	except ValueError:
		port = raw_input("Enter a port number (integer): ")
		continue
	else:
		break
"""
""" http://docs.python.org/2.7/library/socket.html """
for res in socket.getaddrinfo(ip_connect, port, socket.AF_UNSPEC, socket.SOCK_STREAM):
    af, socktype, proto, canonname, sa = res
    try:
        s = socket.socket(af, socktype, proto)
    except socket.error as msg:
        s = None
        continue
    try:
        s.connect(sa)
    except socket.error as msg:
        s.close()
        s = None
        continue
    break
if s is None:
    print 'could not open socket'
    sys.exit(1)

s.sendall(hostname)
clientName = s.recv(1024)
s.close()
print 'Server name : ', repr(clientName)
